### ISSUE TITLE
Unable to use xgboost trained model

### ISSUE THREAD

**Issue by NadirSahllal** [mesalock-linux/gbdt-rs#12]
Hello, 
Thank you for the great library.
I have an issue, I train a model in python using xgboost, but when I try to use "from_xgboost_dump"
I get the following error: thread 'main' panicked at 'failed to load the model: ParseIntError { kind: Empty }'

I was wondering if it would be related to the version of the used xgboost library?!

Thank you

**Comment by w-biggs** [comment]
I get this error as well, with a model trained with xgboost 1.4.0.1

**Comment by CharlieBickerton** [comment]
I also get this error when using the python conversion script

**Comment by CharlieBickerton** [comment]
Hey guys, @NadirSahllal @w-biggs , I've found a solution for this issue. 

If you look at the converted model, you'll see the `"split"` variable. For me this had `"f0"` for my 1st feature and `"f1"` so my second & so on. I compared this with one of the models in this repo and that model had a int for each `"split"` variable. I converted my `"f0"` --> `0` and now the model loads just fine

**Comment by NadirSahllal** [comment]
I Have been meaning to also comment:
I solved the issue also. and apparently it is a version mismatch in from the xgboost. 
The latest version I tried and seems to be working was Xgboost 1.0.2. 
But also in the documentation. When converting, the experiments have only been done on version 0.81 and 0.82
