### ISSUE TITLE
How to specify &[f64] input?

### ISSUE THREAD

**Issue by 0b01** [mesalock-linux/gbdt-rs#7]
I have inference samples encoded as a list of f64. How can I use gbdt to run inference with pretrained xgboost model?

**Comment by litongxin1991** [comment]
You can change the ```ValueType``` to ```f64``` . Then gbdt-rs will support f64. 
See https://github.com/mesalock-linux/gbdt-rs/blob/master/src/decision_tree.rs#L125

README describes the steps to use pretrained  xgboost model. And there are examples in ```examples/test-xgb*```.
You can use ```examples/convert_xgboost.py``` to convert the xgboost model to gbdt-rs model. 
The comments in the examples will show you some detailed commands to use the script.
For example, https://github.com/mesalock-linux/gbdt-rs/blob/master/examples/test-xgb-reg-logistic.rs#L10
