### ISSUE TITLE
Impurity calculation question

### ISSUE THREAD

**Issue by m3ngzhang** [mesalock-linux/gbdt-rs#8]
Here is the get_impurity method in decision_tree.rs:
for pair in sorted_data.iter() {
            let (index, feature_value) = *pair;
            if feature_value == VALUE_TYPE_UNKNOWN {
                let cv: &CacheValue = &cache.cache_value[index];
                s += cv.s;
                ss += cv.ss;
                c += cv.c;
                unknown += 1;
            } else {
                break;
            }
        }
I wanna ask why use break instead of continue to break the loop. I think the purpose of this code is to count and calculate the unknown value of samples.

**Comment by dingelish** [comment]
@litongxin1991

**Comment by litongxin1991** [comment]
The ```sorted_data``` is sorted in ascending order based on the feature_value.  And the ```VALUE_TYPE_UNKNOWN``` equals to the ```VALUE_TYPE_MIN```, that means, it's the minimum f32/f64 value. 	

The samples with unknown feature value will be in the beginning of the ```sorted_data```. In the loop,  when current sample has non-unknown feature value, all the samples with unknown feature value has been counted, so it's ok to break the loop.
